# Generated by Django 5.1.6 on 2025-03-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasker', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in-analysis', 'In Analysis'), ('in-progress', 'In Progress'), ('flagged', 'Flagged'), ('completed', 'Completed')], default='in-analysis', max_length=15),
        ),
    ]
