# Generated by Django 5.1.6 on 2025-03-05 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_of_day',
            field=models.TimeField(),
        ),
    ]
